#!/bin/bash

# Usage: mqtt-grep-colorise <expr> <topic>
# subscribe to the MQTT "topic" (Default: #) and colorise it, optionally grepping for "expr"

# License: GNU General Public License v3.0
# For more information see project "mqtt-grep-colorize" on GitHub.

set -f # no globbing needed or wanted

grepexp="${1:-[\}{]}" # colorize } and {, if no other grep expression given
topic="${2:-#}"       # use # as MQTT topic, if nothing else given
GREPOPTS="-E --line-buffered --color=always"

                        mosquitto_sub -v -t "$topic" \
| GREP_COLOR="01;31"    grep $GREPOPTS "^[^ ]+"      \
| xargs -r -d$'\n' -L1  bash -c 'date "+%T.%1N $0"'  \
| GREP_COLOR="01;33"    grep $GREPOPTS "^..:..:..."  \
| GREP_COLOR="01;32"    grep $GREPOPTS "$grepexp"    \
;
